# Generated by Django 5.1.6 on 2025-03-02 00:13

import media_library.models
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MediaCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("slug", models.SlugField(max_length=100, unique=True)),
            ],
            options={
                "verbose_name_plural": "Media Categories",
            },
        ),
        migrations.CreateModel(
            name="MediaFile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("file", models.FileField(upload_to=media_library.models.upload_to)),
                ("is_verge3d", models.BooleanField(default=False)),
                ("file_type", models.CharField(editable=False, max_length=100)),
                ("alt_text", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("width", models.IntegerField(editable=False, null=True)),
                ("height", models.IntegerField(editable=False, null=True)),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True, to="media_library.mediacategory"
                    ),
                ),
            ],
        ),
    ]
