# Generated by Django 5.1.6 on 2025-03-02 00:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("media_library", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mediafile",
            name="is_verge3d",
        ),
        migrations.AddField(
            model_name="mediafile",
            name="html_index_path",
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
        migrations.AddField(
            model_name="mediafile",
            name="is_html",
            field=models.BooleanField(default=False, verbose_name="HTML Website"),
        ),
    ]
