# Generated by Django 5.1.6 on 2025-03-02 14:37
import os

from django.contrib.auth import get_user_model
from django.db import migrations


def create_superuser(apps, schema_editor):
    User = get_user_model()

    # Create superuser if no users exist
    if User.objects.count() == 0:
        # Get environment variables or use defaults
        admin_email = os.environ.get('DJANGO_ADMIN_EMAIL', 'org-admin@edustartech.com')
        admin_password = os.environ.get('DJANGO_ADMIN_PASSWORD', 'org-admin@edustartech.com')
        User.objects.create_superuser(email=admin_email, password=admin_password)

        print(f"Created superuser with email: {admin_email}")

class Migration(migrations.Migration):
    dependencies = [
        ("media_library", "0001_initial"),
    ]

    operations = [migrations.RunPython(create_superuser, migrations.RunPython.noop)]
