# Generated by Django 5.1.6 on 2025-03-02 01:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("media_library", "0002_remove_mediafile_is_verge3d_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="mediafile",
            name="original_zip_path",
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
    ]
