# Generated by Django 5.1.6 on 2026-03-13 17:00

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("media_library", "0002_create_default_superuser"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mediafile",
            options={"ordering": ["-uploaded_at"]},
        ),
    ]
