# Generated by Django 5.1.6 on 2025-03-02 01:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("media_library", "0003_mediafile_original_zip_path"),
    ]

    operations = [
        migrations.AddField(
            model_name="mediafile",
            name="is_processed",
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AddField(
            model_name="mediafile",
            name="processing_error",
            field=models.TextField(blank=True, editable=False),
        ),
    ]
