# Generated by Django 5.1.6 on 2025-03-02 02:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("media_library", "0004_mediafile_is_processed_mediafile_processing_error"),
    ]

    operations = [
        migrations.AddField(
            model_name="mediafile",
            name="html_base_dir",
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
    ]
