# Generated by Django 5.1.6 on 2025-03-02 14:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("media_library", "0005_mediafile_html_base_dir"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mediafile",
            name="title",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.CreateModel(
            name="MediaUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        help_text="Type of content where media is used (e.g. post, page)",
                        max_length=100,
                    ),
                ),
                (
                    "object_id",
                    models.CharField(
                        help_text="ID of the object where media is used", max_length=100
                    ),
                ),
                (
                    "field_name",
                    models.CharField(
                        help_text="Field name that uses the media", max_length=100
                    ),
                ),
                (
                    "url",
                    models.URLField(
                        blank=True, help_text="External link to where media is used"
                    ),
                ),
                ("date_added", models.DateTimeField(auto_now_add=True)),
                (
                    "media",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usage_locations",
                        to="media_library.mediafile",
                    ),
                ),
            ],
            options={
                "verbose_name": "Media Usage",
                "verbose_name_plural": "Media Usages",
                "unique_together": {
                    ("media", "content_type", "object_id", "field_name")
                },
            },
        ),
    ]
